#!/bin/bash

NEURON=$NEURON_PORT_4006_TCP_ADDR:4006

echo "NEURON IS $NEURON"

if [ "$XS_DEBUG" = 0 ]; then
    echo "No debug ..."
    node server.js proxy_config.json
else
    # called in local mode, so need to add the test user manually
    echo "launching with inspect $(node -v)"
    node --inspect server.js proxy_config.json
fi